# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/android-chrome-192x192.png"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "2006年1月2日"
lastUpdated = "2006年1月2日 15:04"

[sidebar]
emoji = "🍥"
subtitle = ""

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "ovideros/new_blog"
repoID = "R_kgDOPIzbSQ"
category = "Announcements"
categoryID = "DIC_kwDOPIzbSc4CspIa"
mapping = "pathname"
reactionsEnabled = 1
emitMetadata = 0
